import type { Metadata } from "next";
import "./globals.css";
import { HeaderShop } from "@/components/layout/header/header";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { SessionProvider } from "next-auth/react";
import { WhatsAppButton } from "@/components/layout/whatsapp/whatsapp";
import { Footer } from "@/components/layout/footer/footer";
import CatalogLoader from "@/components/layout/load-info-backend/loadInfoBackend";
import { getInfoEcommerce } from "@/services/informacion-tienda/informacion-tienda-services";

export const metadata: Metadata = {
  title: "Ecommerce Ferreteria",
  description: "Generated by create next app",
};

// const phoneNumber = process.env.NEXT_PUBLIC_PHONE_NUMBER;
const phoneNumber =
      (await getInfoEcommerce())?.data.whatsapp ?? process.env.NEXT_PUBLIC_PHONE_NUMBER;

console.log(`WhatsApp Number: ${phoneNumber}`)      

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <>
      <html lang="en" suppressHydrationWarning>
        <head >
             {/* Manifest */}
        <link rel="manifest" href="/icon-app/manifest.json" />

        {/* Iconos */}
        <link
          rel="icon"
          type="image/png"
          sizes="192x192"
          href="/icon-app/android-chrome-192x192.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="512x512"
          href="/icon-app/android-chrome-512x512.png"
        />

        {/* Tema para la barra del navegador en móvil */}
        </head>
        <body className="min-h-screen flex flex-col">
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <SessionProvider>
              <WhatsAppButton phoneNumber={`+52${phoneNumber!}`} />
              <CatalogLoader /> {/* 🔥 Inicializa el catálogo en toda la app */}
              <HeaderShop />
              {/* El contenido crecerá y empujará el footer hacia abajo */}
              <main className="flex-grow">{children}</main>
              {/* <Footer></Footer> */}
            </SessionProvider>
          </ThemeProvider>
          <Footer />
        </body>
      </html>
    </>
  );
}
